# Question 1

In [2]:
def getWordsList(str):
    list=[]
    str = "Hello to 3v3ry Body. Yours’s sincerely. hello I am “Ali”. I AM no body."
    size = len(str.split(' '))
    str.isalnum()
    print(str)
    return size

print(getWordsList(str))

Hello to 3v3ry Body. Yours’s sincerely. hello I am “Ali”. I AM no body.
14

In [43]:
str = "Hello to 3v3ry Body. Yours’s sincerely. hello I am “Ali”. I AM no body."
list=[]
str = str.lower()
print(str)
if word in str.isalnum:
    list.append('word')

hello to 3v3ry body. yours’s sincerely. hello i am “ali”. i am no body.

NameError: name 'word' is not defined

In [ ]:
def printWords(word):
    print(word)
    print(count)
    print(probability)

# Question 2

# PART A

In [ ]:
from mrjob.job import MRJob

class countof_usernames(MRJob):
    
    def mapper(self, _, line):
        parts=line.split(',')
        UserName=parts[0]
        Comment=parts[1]
        yield(UserName,1)
        
    def reducer(self, UserName, count):
        yield(UserName,sum(count))
        
if __name__ = "__main__":
    countof_usernames.run()

# PART C

In [ ]:
from mrjob.job import MRJob

class maximumnumber_comments(MRJob):
    
    def mapper(self, _, line):
        parts=line.split(',')
        UserName=parts[0]
        Comment=parts[1]
        yield(UserName,(Comment,1))
        
    def reducer(self, UserName, count):
        yield(UserName,sum(count).max())
        
if __name__ = "__main__":
    maximumnumber_comments.run()

# Question 3

In [16]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sklearn

In [3]:
data = pd.read_excel("OnlineRetail (1).xlsx")

In [4]:
data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

In [5]:
data.describe()

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB

In [10]:
data = data.drop(['CustomerID'],axis=1)

KeyError: "['CustomerID'] not found in axis"

In [11]:
data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,United Kingdom
...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,France

In [22]:
from sklearn import train_test_split
data = train_test_split(train_size=70 , test_size=30)

ImportError: cannot import name 'train_test_split' from 'sklearn' (C:\ProgramData\Anaconda3\lib\site-packages\sklearn\__init__.py)

In [30]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 7 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64
 6   Country      541909 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(1), object(4)
memory usage: 28.9+ MB

In [31]:
X = data['Quantity']
Y = data['UnitPrice']
data=list(zip(X,Y))

In [34]:
inertias= []

from sklearn.cluster import k_means
kmeans=k_means(n_clusters=3)
kmeans.fit(data)

for i in range (3,6):
    kmeans=k_means(n_clusters=i)
    kmeans.fit(data)
    inertias.append(kmeans.inertias)
    
plt.scatter(range(3,6),inertias,c=kmeans.labels_)
plt.xlabel("Range")
plt.ylabel("Inertias")
plt.title("Elbow Method")
plt.plot()

TypeError: k_means() missing 1 required positional argument: 'X'

In [ ]:
plt.scatter(X,Y,c=kmeans.labels_,cmap="rainbow")
plt.xlabel("Quantity")
plt.ylabel("UnitPrice")
plt.title("K_Measn")
plt.plot()

In [ ]:
from sklearn.metrics import confusion_matrix
plt.plot(confusion_matrix)
print('accuracy':accuracy)